services:
  web:
    image: triangle-pos:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    platform: "linux/amd64"
    image: mysql:latest
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: triangle_pos
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:


